# Generated by Django 4.0.4 on 2022-06-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-fecha_creacion',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
