# Generated by Django 4.0.4 on 2022-06-05 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publicado',
        ),
    ]
